/**
 * Vedra Design Tokens — v1.0
 *
 * Dark palette: deep space base with electric violet + cyan dual-tone accents.
 * Light palette: clean white with deep violet and teal accents.
 */

const colors = {
  light: {
    // Dark theme (Vedra's signature theme)
    background:            '#03030A',
    foreground:            '#F0F4FF',
    card:                  '#0A0A18',
    cardForeground:        '#F0F4FF',
    primary:               '#7C3AED',
    primaryForeground:     '#FFFFFF',
    secondary:             '#0D0D20',
    secondaryForeground:   '#F0F4FF',
    muted:                 '#12122A',
    mutedForeground:       '#4B5280',
    accent:                '#06B6D4',
    accentForeground:      '#03030A',
    accentSecondary:       '#7C3AED',
    listeningRing:         '#10FFAA',
    processingRing:        '#F59E0B',
    destructive:           '#EF4444',
    destructiveForeground: '#FFFFFF',
    border:                '#1A1A35',
    input:                 '#1A1A35',
    text:                  '#F0F4FF',
    tint:                  '#7C3AED',
    glowViolet:            'rgba(124, 58, 237, 0.18)',
    glowCyan:              'rgba(6, 182, 212, 0.12)',
    success:               '#10B981',
    warning:               '#F59E0B',
  },
  dark: {
    // True dark (same as default — Vedra is dark-first)
    background:            '#03030A',
    foreground:            '#F0F4FF',
    card:                  '#0A0A18',
    cardForeground:        '#F0F4FF',
    primary:               '#7C3AED',
    primaryForeground:     '#FFFFFF',
    secondary:             '#0D0D20',
    secondaryForeground:   '#F0F4FF',
    muted:                 '#12122A',
    mutedForeground:       '#4B5280',
    accent:                '#06B6D4',
    accentForeground:      '#03030A',
    accentSecondary:       '#7C3AED',
    listeningRing:         '#10FFAA',
    processingRing:        '#F59E0B',
    destructive:           '#EF4444',
    destructiveForeground: '#FFFFFF',
    border:                '#1A1A35',
    input:                 '#1A1A35',
    text:                  '#F0F4FF',
    tint:                  '#7C3AED',
    glowViolet:            'rgba(124, 58, 237, 0.18)',
    glowCyan:              'rgba(6, 182, 212, 0.12)',
    success:               '#10B981',
    warning:               '#F59E0B',
  },
  lightMode: {
    // Clean light palette for users who prefer it
    background:            '#F8F9FF',
    foreground:            '#0A0A1A',
    card:                  '#FFFFFF',
    cardForeground:        '#0A0A1A',
    primary:               '#6D28D9',
    primaryForeground:     '#FFFFFF',
    secondary:             '#F1F0FF',
    secondaryForeground:   '#1A1A3E',
    muted:                 '#F1F0FF',
    mutedForeground:       '#6B7280',
    accent:                '#0891B2',
    accentForeground:      '#FFFFFF',
    accentSecondary:       '#6D28D9',
    listeningRing:         '#059669',
    processingRing:        '#D97706',
    destructive:           '#DC2626',
    destructiveForeground: '#FFFFFF',
    border:                '#E5E7EB',
    input:                 '#E5E7EB',
    text:                  '#0A0A1A',
    tint:                  '#6D28D9',
    glowViolet:            'rgba(109, 40, 217, 0.10)',
    glowCyan:              'rgba(8, 145, 178, 0.08)',
    success:               '#059669',
    warning:               '#D97706',
  },
  radius: 20,
};

export default colors;
